version: '3'
services:
  app:
    tty: true
    stdin_open: true
    depends_on:
      - db
    image: my_app_image
    volumes:
      - ./:/app
      - /tmp
    ports:
      - 3000:3000
    command: ["sh", "scripts/dev-entrypoint-rails.sh"]
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - my-app-db-data:/var/lib/mysql
      - ./db/initialize:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  adminer:
    image: dockette/adminer
    ports:
      - 8001:80
volumes:
  my-app-db-data:
